### ISSUE TITLE
System library compiled at compile time is not available at runtime

### ISSUE THREAD

**Issue by msrd0** [AdnoC/sixel-sys#3]
This crate builds a dynamic version of libsixel at compile time and links against it. Then, when you run the executable, that library is not found, and relies on you having a dynamic library of libsixel installed on the operating system.

Please change it so that if libsixel is installed, you use the system installed version, and otherwise you compile and statically link against your own compiled version of libsixel. This is how many popular sys crates work in the Rust ecosystem, for example libgit2-sys.

**Comment by AdnoC** [comment]
Hi @msrd0, I believe I got it to statically link the C library. I've tried to verify this with several ways, but I'm not that familiar with this. Can you check that this is properly handled?

**Comment by msrd0** [comment]
So in order to test that I'd compile a binary and use `ldd` to see if it links against some unknown library. You have tests so those compile to a binary so I tried to compile them (latest commit is b01a5ba1e44b04413f64f6e77c1490bbdfe943ea). Looks like your build script is now broken unfortunately

```
$ cargo test --no-run
warning: no edition set: defaulting to the 2015 edition while the latest is 2024
    Updating crates.io index
[...]
   Compiling shlex v1.3.0
   Compiling make-cmd v0.1.0
   Compiling lazy_static v0.2.11
   Compiling cc v1.2.15
   Compiling autotools v0.2.7
   Compiling sixel-sys v0.5.0 (/home/msrd0/git/sixel-sys)
warning: unused import: `make_cmd::make`
 --> build.rs:7:5
  |
7 | use make_cmd::make;
  |     ^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `std::fs::canonicalize`
  --> build.rs:11:5
   |
11 | use std::fs::canonicalize;
   |     ^^^^^^^^^^^^^^^^^^^^^

warning: `sixel-sys` (build script) generated 2 warnings
warning: sixel-sys@0.5.0: WITHOUT PNG
error: failed to run custom build command for `sixel-sys v0.5.0 (/home/msrd0/git/sixel-sys)`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_TEST_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/home/msrd0/git/sixel-sys/target/debug/build/sixel-sys-c1d40eb82e009bb6/build-script-build` (exit status: 101)
  --- stdout
  cargo::warning=WITHOUT PNG
  running: cd "/home/msrd0/git/sixel-sys/libsixel" && "sh" "-c" "exec \"$0\" \"$@\"" "autoreconf" "-ivf"

  --- stderr
  autoreconf: export WARNINGS=
  autoreconf: error: 'configure.ac' is required

  thread 'main' panicked at /usr/local/share/rust/registry/src/github.com-25cdd57fae9f0462/autotools-0.2.7/src/lib.rs:790:5:

  command did not execute successfully, got: exit status: 1

  build script failed, must exit now
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/std/src/panicking.rs:692:5
     1: core::panicking::panic_fmt
               at /rustc/4d91de4e48198da2e33413efdcd9cd2cc0c46688/library/core/src/panicking.rs:75:14
     2: autotools::fail
     3: autotools::Config::build
     4: build_script_build::main
     5: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by msrd0** [comment]
Oh wait nvm you use git submodules. Seems to work now.

**Comment by msrd0** [comment]
Btw you might want to make sure you only write files to the directory the env variable `OUT_DIR` points to. Build scripts are unfortunately not usually sandboxed, but shouldn't just write to any location, and some tools like docs.rs also seem to enforce that: https://docs.rs/crate/sixel-sys/0.5.0/builds/1794427

**Comment by AdnoC** [comment]
I know. I'm trying to get this and [sixel-rs](https://github.com/AdnoC/sixel-rs) into a state that isn't embarrassing, but its going to be a slow process. Thank you for finding this useful.
